### ISSUE TITLE
Add highlight for WinSeparator

### ISSUE THREAD

**Issue by ghost** [water-sucks/darkrose.nvim#1]
Nvim is deprecating VertSplit and moving to WinSeparator for window borders in 0.10. By default, WinSeparator links to normal which does not look great for most colorschemes.

**Comment by water-sucks** [comment]
Hey thanks for the issue! Done in [10a8b02](https://github.com/water-sucks/darkrose.nvim/commit/10a8b028c8757167d132b33902156e91ad8ab357).
