### ISSUE TITLE
what is the bar you use in the screenshot?

### ISSUE THREAD

**Issue by jabuxas** [water-sucks/darkrose.nvim#2]
looks good

**Comment by water-sucks** [comment]
The bottom bar is `lualine.nvim` with a custom theme, config for it is [here](https://github.com/water-sucks/nixed/blob/0368ad5bf02475b877ca5507cab898905c98faf4/home/profiles/base/nvim/lua/plugins/lualine.lua); the top is `bufferline.nvim`, config for it is [here](https://github.com/water-sucks/nixed/blob/0368ad5bf02475b877ca5507cab898905c98faf4/home/profiles/base/nvim/lua/plugins/bufferline.lua)

Also thanks for the compliment :}

**Comment by jabuxas** [comment]
ty a lot :D
