### ISSUE TITLE
Enable/disable italics

### ISSUE THREAD

**Issue by slowpuke** [water-sucks/darkrose.nvim#3]
I am very grateful for the introduction of the opt in function for italics/bold/underline, however I wasn't able to disable the italics for a long time until today. 
The docs say the option should be set to `italics = false` however only when set to `italic = false` the option actually worked. 
I don't know if this is a me issue, or if there is a discrepancy between the docs and the colorscheme itself so I didn't make a PR.

**Comment by water-sucks** [comment]
Hey! Sorry for getting back so late. I made a spelling mistake in the docs, so that's fun 😆. Thanks for pointing me to this!

**Comment by water-sucks** [comment]
Fixed in [54f8f6e2ea85c04dcd21af5b6f2eda95b29982a8](https://github.com/water-sucks/darkrose.nvim/commit/54f8f6e2ea85c04dcd21af5b6f2eda95b29982a8).
