### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by KonstantinosTsitoumis** [water-sucks/darkrose.nvim#4]
Hello! 

I really like this theme, I was wondering if it's possible to make the background transparent while using it. 
If this is already supported, could you provide me some guidance on how to do that?

Thanks for your help!

**Comment by water-sucks** [comment]
Hey! I haven't explicitly supported this use case, since I'm not quite sure if it will look good, but it should be possible to use a plugin like [xiyaowong/transparent.nvim](https://github.com/xiyaowong/transparent.nvim) to achieve that end.

Note that your terminal has to support it as well.
