### ISSUE TITLE
Too much red

### ISSUE THREAD

**Issue by MattRStoffel** [water-sucks/darkrose.nvim#5]
Please revise color scheme to be more like water.

**Comment by water-sucks** [comment]
Hi Matt,

Thanks for checking out my color scheme bro! Appreciate the view.

You might not like it, but these are the colors I chose for my own enjoyment; they're my favorite colors, after all. Minor color adjustments are possible but I'm not going to just remove red from the equation just for a single person 🫠 

You can override colors yourself if you would like, using the `colors` key in the setup function. See [the colors file](https://github.com/water-sucks/darkrose.nvim/blob/main/lua/darkrose/colors.lua) for a reference on what colors are available.

Also, did you know 100% of people who drink water die? Maybe the water suggestion isn't in good taste, for me at least ;}
